url: https://speedyvelcro.com
collections_dir: collections

collections:
  music:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "music"
      permalink: "/music/:title/"
